% enum off, standby, active, etc

carFeatureStatus = struct( ...
    'CACC', 0, ...
    'ACC', 0, ...
    'AIN', 0, ...
    'LCC', 0, ...
    'AP', 0 ...
);

carSwitches = struct(...
    'V2X', 0, ...
    'LongSwitch', 0, ...
    'LatSwitch', 0 ...
)

carMainDriveInputs = struct(...
    'Speed', 0, ...
    'Brake_Pressed', 0 ...
);

carManualControlInputs = struct(...
    'Enable_ACC', 0, ...
    'Enable_AIN', 0, ...
    'Enable_CACC', 0, ...
    'Enable_LCC', 0, ...
    'Enable_AP', 0, ...
    'Cancel_Button', 0, ...
    'Set_Button', 0, ...
    'Finish_Button', 0 ...
);

carSensorInputs = struct(...
    'Lane_Detected', 0, ...
    'Parking_Space_Distance', 0, ...
    'Lane_Centered', 0 ...
);