% Autogenerated file: Fri Dec  5 15:50:34 2025
function writeCodeInfoFcn


% Load a ComponentInterface object from IR
codeIRInfoStruct = load('tlc\codeIRInfo.mat');
codeInfo = codeIRInfoStruct.codeInfo;



wr = coder.internal.writeDataInterfacesToCodeDescriptor("acc_vm",pwd);
wr.writeName(codeInfo.Name);
% Need to call componentInterface 'getParameters' before deleting any Parameter DataInterfaces to avoid crash.
wr.fFullModel.componentInterface.Parameters;

    
    
    

    

    skippedParametersInterfaceInfo = [];
    skippedParametersIndex = [];
    
    
                
            
            

    





                        
            

            % Opaque Data Type
            type_RTModel = coder.descriptor.types.Opaque(wr.fMF0Model);
            type_RTModel.Identifier = 'RT_MODEL_acc_vm_T';
            

        % Pointer Type: Pointer to type_RTModel
        CodeDescPtrtype_RTModel_1_0 = coder.descriptor.types.Pointer(wr.fMF0Model);
            CodeDescPtrtype_RTModel_1_0.BaseType = type_RTModel;
        CodeDescPtrtype_RTModel_1_0.ReadOnly = 1;
        CodeDescPtrtype_RTModel_1_0.Volatile = 0;
        
        wr.addGetRTMToModelClass("getRTM", CodeDescPtrtype_RTModel_1_0);
        wr.addSetRTMToModelClass("setRTM", CodeDescPtrtype_RTModel_1_0);
        wr.addRTMTypeToModelClassElements(CodeDescPtrtype_RTModel_1_0.BaseType, "acc_vm_M");


        
        

    

    

    

    
    

    








            wr.removeSkippedParameters(skippedParametersInterfaceInfo);

    

    
    
    

    

    
    
                        

        
        

    

    

    

            if ~isempty(skippedParametersIndex)
        codeInfo.Parameters(skippedParametersIndex) = [];
        end

    

% Handling Right-Click Builds
ss = rtwprivate('getSourceSubsystemHandle',codeInfo.GraphicalPath);
% Check if Rt-Click build, then re-map SIDs
wr.commitAndBeginNewTransaction();
if ~isempty(ss) && rtwprivate('rtwattic','hasSIDMap')
wr.fFullModel.componentInterface = modifyCodeInfoForSubsystemBuild(ss, wr.fFullModel.componentInterface);
codeInfo = modifyCodeInfoForSubsystemBuild(ss, codeInfo);
end

wr.writeDataInterfacesLate();
wr.fixUpInternalDataAndUpdateLate();

    wr.ConstructorArgumentFixup;
    







wr.closeRepo();

    if exist('expInports', 'var')
    save codeInfo.mat codeInfo expInports;
    else
    save codeInfo.mat codeInfo;
    end
returnVal = 1;

% End Function: writeCodeInfoFcn

function idx = findArrayValueIdx(internalIdVec, internalId)
if isa(internalIdVec, 'mf.zero.PrimitiveSequence')
idx = find(internalIdVec.toArray == internalId);
else
idx = find(internalIdVec == internalId);
end

function arraySize = getArrayOrSequenceSize(arrayOrSequence)
if isa(arrayOrSequence, 'mf.zero.Sequence')
arraySize = length(arrayOrSequence.toArray);
return;
end
arraySize = length(arrayOrSequence);

function data = uniquifyDataAccess(list)
data = [];
for idx=1:getArrayOrSequenceSize(list)
if ~isPresentDI(data, list(idx)) %#ok<AGROW>
if isempty(data)
data = list(idx);
else
data(end+1) = list(idx);
end
end
end
% End Function: uniquifyDataAccess

function isPresent = isPresentDI(list, di)
isPresent = false;
for idx = 1:numel(list)
if isequal(list(idx), di)
isPresent = true;
break
end
end

function idx = getIndexFromTimingInternalId(internalIdVec, internalId)
idx = findArrayValueIdx(internalIdVec, internalId);
if (isempty(idx) || (length(idx) > 1))
ciMsg = 'Time object cannot be empty';
ciExc = MException('RTW:buildProcess:CodeInfoInternalError',ciMsg);
throw(ciExc);
end
% End Function: getIndexFromTimingInternalId

function checkDataGraphicalNames(ciName, rtwName)
if (startsWith(ciName, 'BlockParam:'))
tokens = split(ciName, ':');
ciName = tokens{2};
end
if (strcmp(ciName, rtwName) ~= 1)
ciMsg = ['Name mismatch: ', ciName, ' and ', rtwName];
ciExc = MException('RTW:buildProcess:CodeInfoInternalError',ciMsg);
throw(ciExc);
end
% End Function: checkDataGraphicalNames

function iData = getInternalDataByName(iDataVec, iDataName)
if isa(iDataVec, 'mf.zero.Sequence')
iData = coder.descriptor.DataInterface.empty;
iDataVec = iDataVec.toArray;
else
iData = RTW.DataInterface.empty;
end
for idxData = 1:numel(iDataVec)
if strcmp(iDataName, iDataVec(idxData).GraphicalName)
iData(end+1) = iDataVec(idxData);
break
end
end
if (isempty(iData) || (length(iData) > 1))
ciMsg = 'Internal Data object cannot be empty';
ciExc = MException('RTW:buildProcess:CodeInfoInternalError',ciMsg);
throw(ciExc);
end
% End Function: getInternalDataByName

function iData = getInternalDataByVariableName(iDataVec, iDataVariableName)
if isa(iDataVec, 'mf.zero.Sequence')
iData = coder.descriptor.DataInterface.empty;
iDataVec = iDataVec.toArray;
else
iData = RTW.DataInterface.empty;
end
for idxData = 1:numel(iDataVec)
if strcmp(iDataVariableName, iDataVec(idxData).Implementation.VariableName)
iData = iDataVec(idxData);
break
end
end
if isempty(iData)
ciMsg = 'Internal Data object cannot be empty';
ciExc = MException('RTW:buildProcess:CodeInfoInternalError',ciMsg);
throw(ciExc);
end
% End Function: getInternalDataByVariableName

function addValuesToSequence(aSequence, aValues)
for idx = 1:getArrayOrSequenceSize(aValues)
aSequence.add(aValues(idx));
end

function componentInterface = modifyCodeInfoForSubsystemBuild(ss, componentInterface)
    % Extract Subsystem Build Map from AtticData
    Subsystem_Build_Mapping = rtwprivate('rtwattic','getSIDMap');

    % Parameters
    for i = 1:getArrayOrSequenceSize(componentInterface.Parameters)
    sid = componentInterface.Parameters(i).SID;

    componentInterface.Parameters(i).SID = Simulink.ID.getSubsystemBuildSID(sid, ss, Subsystem_Build_Mapping);
    end

    % Data Stores
    for i = 1:getArrayOrSequenceSize(componentInterface.DataStores)
    sid = componentInterface.DataStores(i).SID;

    componentInterface.DataStores(i).SID = Simulink.ID.getSubsystemBuildSID(sid,ss, Subsystem_Build_Mapping);
    end

    % Inports
    for i = 1:getArrayOrSequenceSize(componentInterface.Inports)
    sid = componentInterface.Inports(i).SID;

    componentInterface.Inports(i).SID = Simulink.ID.getSubsystemBuildSID(sid,ss, Subsystem_Build_Mapping);
    end

    % Outports
    for i = 1:getArrayOrSequenceSize(componentInterface.Outports)
    sid = componentInterface.Outports(i).SID;

    componentInterface.Outports(i).SID = Simulink.ID.getSubsystemBuildSID(sid,ss, Subsystem_Build_Mapping);
    end

